name: Train and Save Model

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  push:
    branches:
      - main # Or your default branch, if different

jobs:
  train_and_save_model:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # Specify the Python version you need

    - name: Install dependencies
      run: |
        pip install pandas scikit-learn joblib

    - name: Run the model training script
      run: python diabetes_prediction.py

    - name: Commit and push the trained model
      run: |
        git config --global user.name 'Your Name'
        git config --global user.email 'your-email@example.com'
        git add dia_risk_prediction_model.pkl
        git commit -m "Add trained model"
        git push
